export interface GateHistoryEntry {
  verdict: string
  change?: string
  issues?: Array<{ code?: string; message?: string; rule_id?: string }>
  trust_score?: number
  timestamp?: string
}

export interface LessonSummary {
  what_passed: string[]
  what_was_caught: string[]
  gate_misses: string[]
  policy_candidates: string[]
  new_checklist_candidates: string[]
  reusable_patterns: string[]
  antipatterns: string[]
  auto_applied: false
}

export function extractLessons(gateHistory: GateHistoryEntry[]): LessonSummary {
  const what_passed = gateHistory
    .filter(g => g.verdict === 'PASS' || g.verdict === 'PASS_WITH_WARNINGS')
    .map(g => g.change ?? `(change at ${g.timestamp ?? 'unknown'})`)

  const caught = gateHistory
    .filter(g => g.verdict !== 'PASS' && g.verdict !== 'PASS_WITH_WARNINGS')
    .flatMap(g => g.issues?.map(i => i.message ?? i.code ?? 'unknown issue') ?? [])

  const policy_candidates = gateHistory
    .filter(g => g.verdict === 'BLOCK' || g.verdict === 'REVISE')
    .flatMap(g =>
      (g.issues ?? []).map(
        i => `[POLICY_CANDIDATE] ${i.rule_id ?? i.code ?? 'UNKNOWN'}: ${i.message ?? '(no message)'}`,
      )
    )

  return {
    what_passed,
    what_was_caught: caught,
    gate_misses: [],
    policy_candidates,
    new_checklist_candidates: [],
    reusable_patterns: [],
    antipatterns: [],
    auto_applied: false,
  }
}

export function formatLessonsMarkdown(lessons: LessonSummary): string {
  return `# Lessons

## What Passed
${lessons.what_passed.map(x => `- ${x}`).join('\n') || '- (none)'}

## What Gate Caught
${lessons.what_was_caught.map(x => `- ${x}`).join('\n') || '- (none)'}

## Gate Misses
${lessons.gate_misses.map(x => `- [GATE_MISS] ${x}`).join('\n') || '- (none yet — add manually after post-release incidents)'}

## Policy Candidates
${lessons.policy_candidates.map(x => `- ${x}`).join('\n') || '- (none)'}

## New Checklist Candidates
${lessons.new_checklist_candidates.map(x => `- ${x}`).join('\n') || '- (none)'}

## Reusable Patterns
${lessons.reusable_patterns.map(x => `- ${x}`).join('\n') || '- (none)'}

## Antipatterns
${lessons.antipatterns.map(x => `- ${x}`).join('\n') || '- (none)'}

---
*auto_applied: false — policy_candidates require human review before applying to gate-policy.yml*
`
}

export function generatePolicyDiff(lessons: LessonSummary): string {
  if (lessons.policy_candidates.length === 0) return ''
  const rules = lessons.policy_candidates.map((c, i) => {
    const ruleId = c.match(/\[POLICY_CANDIDATE\]\s+(\S+):/)?.[1] ?? `LEARNED_${i + 1}`
    const message = c.replace(/^\[POLICY_CANDIDATE\]\s+\S+:\s*/, '')
    return `  - rule_id: ${ruleId}\n    description: "${message}"\n    source: learn_loop\n    status: candidate`
  })
  return `# gate-policy.diff.yml — REVIEW BEFORE APPLYING\n# Generated by learn loop — do not auto-apply\nadditional_rules:\n${rules.join('\n')}\n`
}
